### ISSUE TITLE
[trac #245] Trunk doesn't build on OS X 10.5 (Leopard)

### ISSUE THREAD

**Issue by lkarsten** [lkarsten/testrepo#245]
ISSUE 245 IMPORTED FROM TRAC FOR INDEXING.
Tried to build the latest trunk version (2659) on OS X but got a compile error:
```
mgt_param.c:690:2: error: invalid preprocessing directive #elseif
```
After making the following changes the problem was fixed:
```
Index: bin/varnishd/mgt_param.c
===================================================================
--- bin/varnishd/mgt_param.c    (revision 2659)
+++ bin/varnishd/mgt_param.c    (working copy)
@@ -687,7 +687,7 @@
                MUST_RELOAD,
 #ifdef __APPLE__
                "exec cc -dynamiclib -Wl,-undefined,dynamic_lookup -o %o %s"
-#elseif defined(__SOLARIS__)
+#elif defined(__SOLARIS__)
                "exec cc -shared -fpic -c %o %s"
 #else /* default: GCC on Linux & FreeBSD */
                "exec cc -fpic -shared -Wl,-x -o %o %s"
```
