### ISSUE TITLE
[trac #49] building fails on mac osx

### ISSUE THREAD

**Issue by lkarsten** [lkarsten/testrepo#49]
ISSUE 49 IMPORTED FROM TRAC FOR INDEXING.
I'm trying to get it to build on my mac (osx, 10.4), but it fails halfway the Make step.

Where it starts to fail:

```
Making all in varnishd
if gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../../include   -include config.h -O2 -pipe -Wall -Wno-unused-parameter -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wcast-align -Wunused-parameter -Wchar-subscripts -Winline -Wnested-externs -Wredundant-decls -Wformat -O -g -fno-inline -MT varnishd-cache_acceptor.o -MD -MP -MF ".deps/varnishd-cache_acceptor.Tpo" -c -o varnishd-cache_acceptor.o `test -f 'cache_acceptor.c' || echo './'`cache_acceptor.c; \
then mv -f ".deps/varnishd-cache_acceptor.Tpo" ".deps/varnishd-cache_acceptor.Po"; else rm -f ".deps/varnishd-cache_acceptor.Tpo"; exit 1; fi
cache_acceptor.c: In function 'vca_acct':
cache_acceptor.c:170: warning: implicit declaration of function 'clock_gettime'
cache_acceptor.c:170: warning: nested extern declaration of 'clock_gettime'
cache_acceptor.c:170: error: 'CLOCK_REALTIME' undeclared (first use in this function)
cache_acceptor.c:170: error: (Each undeclared identifier is reported only once
cache_acceptor.c:170: error: for each function it appears in.)
{standard input}:375:non-relocatable subtraction expression, "_tv_rcvtimeo" minus "L00000000002$pb"
{standard input}:375:symbol: "_tv_rcvtimeo" can't be undefined in a subtraction expression
{standard input}:374:non-relocatable subtraction expression, "_tv_rcvtimeo" minus "L00000000002$pb"
{standard input}:374:symbol: "_tv_rcvtimeo" can't be undefined in a subtraction expression
{standard input}:366:non-relocatable subtraction expression, "_need_rcvtimeo" minus "L00000000002$pb"

......

{standard input}:100:symbol: "_need_linger" can't be undefined in a subtraction expression
{standard input}:93:non-relocatable subtraction expression, "_linger" minus "L00000000001$pb"
{standard input}:93:symbol: "_linger" can't be undefined in a subtraction expression
{standard input}:92:non-relocatable subtraction expression, "_linger" minus "L00000000001$pb"
{standard input}:92:symbol: "_linger" can't be undefined in a subtraction expression
make[3]: *** [varnishd-cache_acceptor.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

I ran configure with the recommended "./configure --enable-debugging-symbols --enable-developer-warnings --prefix=/opt/varnish".

Any other input that's needed?
